version: "3"
services: 
 web:
  image: ppc64le/hello-world 
  deploy:
   replicas: 3
   resources:
    cpus: "0.1"
    memory: 10M
   restart_policy:
    condition: on-failure
  ports:
      - "80:80"
  networks:
      - webnet
networks:
  webnet:
